### ISSUE TITLE
Icon and splashcreen news

### ISSUE THREAD

**Issue by alebupal** [webprofusion/apetools#14]
Hello, I have a app in Cordova and I need this icons a spashcreen. Is it possible to add them to the web?
These new icons are due to the new smartphones. And they are necessary to upload the app.

ICON/IOS:
```
icon-20.png -> 20 x 20 px
icon-24@2x.png -> 48 x 48 px
icon-27.5@2x.png -> 55 x 55 px
icon-44@2x.png -> 88 x 88 px
icon-86@2x.png -> 172 x 172 px
icon-98@2x.png -> 196 x 196 px
```

SPLASHCREEN/IOS:
```
Default@2x~ipad~anyany.png -> 2732 x 2732 px
Default@2x~ipad~comany.png -> 1278 x 2732 px
Default@2x~iphone~anyany.png -> 1334 x 1334 px
Default@2x~iphone~comany.png -> 750 x 1334 px
Default@2x~iphone~comcom.png -> 1334 x 750 px
Default@3x~iphone~anyany.png -> 2208 x 2208 px
Default@3x~iphone~anycom.png -> 2208 x 1242 px
Default@3x~iphone~comany.png -> 1242 x 2028 px
Default-2436h.png -> 1125 x 2436 px
Default-Landscape-2436h.png -> 2436 x 1125 px
```

a greeting and thanks for the web!

**Comment by webprofusion-chrisc** [comment]
Hi! A pull request for the changes would be appreciated, you need to modify https://github.com/webprofusion/apetools/blob/master/src/models/platformFileSpecs.ts

**Comment by webprofusion-chrisc** [comment]
Thanks for providing the pull request, it's very much appreciated. Published to live now.
