### ISSUE TITLE
Also generate config.xml for the icons

### ISSUE THREAD

**Issue by mesqueeb** [webprofusion/apetools#17]
Hi!
I used your wonderful tool to generate icons:
https://apetools.webprofusion.com/app/#/tools/imagegorilla

However, it's really difficult if I have to manually write every single path to all these icons in my config.xml. Could you add the option to give us some text that we can copy and paste in our config.xml?

Cheers!

**Comment by webprofusion-chrisc** [comment]
@mesqueeb sounds like you're using cordova, are you also using Ionic or something else? Ionic has a set of icon paths in the default config (like this: https://github.com/ionic-team/ionic-conference-app/blob/master/config.xml) which you can copy.

**Comment by mesqueeb** [comment]
I ended up using the npm library called cordova-icon which does everything for me from cli. Feel free to close this. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
