### ISSUE TITLE
Splashscreens are not always sizing to fit in the allocated space

### ISSUE THREAD

**Issue by webprofusion-chrisc** [webprofusion/apetools#2]
Splashscreens should size to fit the available area of the output (such as 800x480) and maintain their aspect ratio. Currently aspect ratio is maintained but some orientations are not centred/fitted.

**Comment by AndyNormore** [comment]
I agree with this guy. Great tool and all, but the images dont fill the screen :(

**Comment by webprofusion-chrisc** [comment]
@AndyNormore thanks for the feedback, are you using square images or are they rectangular?

**Comment by AndyNormore** [comment]
Hey pal, the upload screen says to use 2208 x 2208 and keep the important stuff in the middle. 

Yet, I see that in the preview layouts, the top and bottom 1/3'rds are blank. This, it makes me sad.

**Comment by webprofusion-chrisc** [comment]
@AndyNormore  Have you got an example image? In my tests it looks like this:

![image](https://user-images.githubusercontent.com/2445502/34452209-522376fe-ed75-11e7-9251-42a5793ed84f.png)

For splashscreens images are never stretched, they're just centred with the best fit. We sample the colour of the top left of the splashscreen and use that as the background fill colour.

**Comment by webprofusion-chrisc** [comment]
Resolved.
