### ISSUE TITLE
/iOS/Appicon.appiconset/83.5@x2 incorrect size

### ISSUE THREAD

**Issue by adamnoor** [webprofusion/apetools#21]
The icon generated with this file name is twice the size that is expected.

Expected: 167x167
Actual: 334x334

possible cause: name is not consistent with other similar icons.

Icon 76x76@1x.png
Icon 76x76@2x.png
Icon 83.5@2x.png

apetools/src/models/platformFileSpecs.ts

![ApeToolsCodeScreenshot](https://user-images.githubusercontent.com/7605024/55349211-1b7ce980-5487-11e9-9518-5eb859ebc9f4.png)

**Comment by webprofusion-chrisc** [comment]
Thanks @adamnoor the issue in that filespec is the 2 just before the closing bracket - that's the multiplier. and it should be set to 1 because the res has already been doubled in the spec to 167x167. Pull requests accepted :)

**Comment by webprofusion-chrisc** [comment]
Thanks! PR #22 merged and published to live now.
