### ISSUE TITLE
No splash screens generating for iOS?

### ISSUE THREAD

**Issue by caseyarendt** [webprofusion/apetools#3]
Uploading a 2048x2048 PNG as instructed generates an iOS package without any splash screens listed.

**Comment by iamgbsmith** [comment]
@caseyarendt if you look at the code in tools.ts you can see that the iOS Splash imageSet array has no entries, hence no splash icons are generated. If you want to generate the icons, clone the repo and add the code back in by looking at the initial commit for tools.ts [here](https://github.com/webprofusion/apetools/blob/67914c0542aa09571a39b1da7830d4becad4890d/src/components/tools/tools.ts). It will then generate splash icons.

I couldn't find anything to suggest that Splash icons are no longer used in iOS although [Apple guidelines on Launch Screens](https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/launch-screen/) might be of use. Cheers.

**Comment by webprofusion-chrisc** [comment]
@iamgbsmith I was toying with the idea of adding it back in as either a "legacy ios" bundle or just including it in the current iOS bundle. The reference to deprecated use of splashscreen images is here: https://developer.apple.com/library/content/documentation/Xcode/Reference/xcode_ref-Asset_Catalog_Format/LaunchImageType.html but as I can see from your own link Apple seem to have backed off from that a little in their language.

I would really like if someone could chip in with a pull request or two  for suggested changes (ideally one PR per change). I don't have a lot of time to improve this at the moment but it's not massively difficult as most of the hard bits (resizing and bundling) are already done. The main driver for this version was to move away from the server side processing which was costing me a lot in AWS bandwidth.

**Comment by webprofusion-chrisc** [comment]
iOS launchscreen assets are now included in the bundle. Please open a new issue if there are corrections/omissions, or better yet a pull request :)
