### ISSUE TITLE
ready xml file where found

### ISSUE THREAD

**Issue by lse123** [webprofusion/apetools#34]
I generated icons/splashScreens
phonegap mainly for iOS
Is any ready-made config.xml point to the generated icon files ...?

**Comment by webprofusion-chrisc** [comment]
Hi, no there is currently there is no ready-made config.xml.

**Comment by lse123** [comment]
thank you for quick reply

I have xcode on my MBP

can create this xml file in xcode, and after copy-paste to config.xml in my text editor???

**Comment by webprofusion-chrisc** [comment]
Hi, this is out of scope for this project but here is an example config.xml (from Ionic): https://github.com/ionic-team/ionic-app-base/blob/master/config.xml

**Comment by lse123** [comment]
OK
