### ISSUE TITLE
Docker Container and Compose Script

### ISSUE THREAD

**Issue by jbravo94** [webprofusion/apetools#50]
I can implement that if thats ok.

**Comment by webprofusion-chrisc** [comment]
Hi! This app is built as a static site, so it doesn't have a server side component or API and it can be hosted on anything. I can't see any specific need for a docker container? Let me know if I'm missing something.

**Comment by jbravo94** [comment]
You are right and thats very cool, but now for example i wanted to compile it an run it locally and stumble across the usual problems like which Node version and then JSZip does not want to load etc. and when i just had the possibility to clone the repo and execute a docker-compose script and could have worked with it immediately locally - that was just my point :)

**Comment by webprofusion-chrisc** [comment]
Thanks, that sounds like a devcontainer: https://code.visualstudio.com/docs/remote/devcontainerjson-reference

Yes, I'd be happy to accept a PR for a container/compose script or devcontainer setup :)

If alternatively you'd like to upgrade the project to the latest node and npm dependencies that's fine as well.
