### ISSUE TITLE
iPhoneX Portrait and Landscape support

### ISSUE THREAD

**Issue by lucianomlima** [webprofusion/apetools#6]
Apetools don't generate splash screen files to new Apple devices.
Maybe the recommended image upload dimensions should be set to 2436x2436.

**Comment by perrosnk** [comment]
Any updates on this?

**Comment by webprofusion-chrisc** [comment]
New splashcreen specs have been added, you can also feed it any image size of the right proportions if you want to start with a higher resolution image.
