### ISSUE TITLE
Itunes store operation failed for react-native

### ISSUE THREAD

**Issue by ahmetilhann** [webprofusion/apetools#7]
I make splash screen and apply it. He works on the emulator and on the phone. But when I try to archive and store it, I get this error. I use react-native. Is there a missing picture or something.

<img width="692" alt="ekran resmi 2018-02-14 18 29 30" src="https://user-images.githubusercontent.com/5680957/36245944-78ffc726-123e-11e8-99f6-e9e6ccc0880f.png">

**Comment by ahmetilhann** [comment]
I tried it again and again. He accepted. But I still do not understand why

**Comment by webprofusion-chrisc** [comment]
Please reopen if this issue persists
