### ISSUE TITLE
Please provide sample PSD or AI files

### ISSUE THREAD

**Issue by cyclops24** [webprofusion/apetools#9]
Hi Thanks for this tools.
Please provide sample PSD or AI file to know punch area.

I also suggest to provide old version online too because for me new version generate wrong splash image :disappointed:

**Comment by arcollector** [comment]
@webprofusion-chrisc we need the old version of your website, the same splash screen that i used back in Nov 9, 2017, now the same image, produces an erroneus image, i try to use the initial commits of your repo, but the image is still incorrect, not the same as back in Nov 9, 2017, please help, your tool is the only one in the entire world that makes good splash screens

**Comment by webprofusion-chrisc** [comment]
Hi, the old version uses too much bandwidth on the server and is much too expensive to run for free. This version is the intended replacement but I don't have time to work on it. If you can clone it, fix it and submit a PR then we can get it updated. I'm happy to answer questions. The thing that derailed this version was the js resize library we used isn't compatible with all the common browsers (possibly since they patched for security flaws) and the maintainer of that doesn't have the time to investigate either.

**Comment by webprofusion-chrisc** [comment]
Yes, the tool was server based meaning it uploaded the images to the server then prepared  zip file of all the resized images and let you download that (usually about 32MB per user). That added up to many GB per day in data transfer fees (AWS).

This version (which went live around December) does everything in the users browser using JS so it doesn't incur the data transfer.

**Comment by arcollector** [comment]
but the resizing process was always did it at the client side, with the pica library?

**Comment by webprofusion-chrisc** [comment]
Hi, no the app here (on github) is completely new and made to look like the old version. The old version was server side .net mvc using ImageSharp library to resize. This version is indeed using pica but there is a resize bug in firefox & safari which doesn't show up in the pica demo app, therefore they (pica js) won't consider it a bug. 

Either we're doing something to cause the bug (and pica is fine) or it's their bug but it looks like they don't really want to fix stuff anyway (presumably they also don't have time) so ideally we'd find an alternate library to do high quality resizing in js. Currently just resizing using the html canvas only has too many aliasing artifacts.

**Comment by webprofusion-chrisc** [comment]
Pica have updated their library and our app has now been updated using that. Seems to be working OK now (Chrome and Firefox).

**Comment by arcollector** [comment]
its not working for me, here my splash

![splash](https://user-images.githubusercontent.com/1631140/38038259-f2e5c15a-3280-11e8-89f0-7f00411bf488.png)

**Comment by webprofusion-chrisc** [comment]
@arcollector thanks, I see. The tests I use don't have a gradient and have a larger logo at the center. I think for you we need an option to crop from the center (currently we resize from the center). This option was originally planned but hasn't been implemented yet.

**Comment by webprofusion-chrisc** [comment]
Closing as resolved. Note that we sample the top left colour as the background, so gradients will not render correctly currently. Please request support for background gradients as a new issue if required.
